server:
  port: 9090
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com 
    port: 587
    protocol: smtp
    username: qppk123@gmail.com
    password: skrbxo12
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    maria:
      jdbc-url: jdbc:mariadb://localhost:3306/competition?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: skrbxo12!@
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: true
    properties:
      hibernate:  
        format_sql: true
        hbm2ddl:
          auto: create
    generate-ddl: true
